
platform :ios, '8.2'
use_frameworks!

target 'SambaTechMovied' do
    pod 'Alamofire', '~> 3.0.0'
    pod 'AlamofireObjectMapper', '~> 1.1.0'
    pod 'SwiftLoader'
    pod 'KFSwiftImageLoader'
end

target 'SambaTechMoviedTests' do

end

target 'SambaTechMoviedUITests' do

end

