
platform :ios, '8.2'
use_frameworks!

target 'SambaTechMovied' do
    pod 'Alamofire', '~> 3.0.0'
    pod 'AlamofireObjectMapper', '~> 1.1.0'
    pod 'SwiftLoader'
    pod 'KFSwiftImageLoader'
    pod 'ActionSheetPicker-3.0', '~> 2.0.4'
    pod 'ReachabilitySwift'
    pod 'JLToast', '~> 1.3'
    pod 'SKPhotoBrowser'
    pod 'RealmSwift'
end

target 'SambaTechMoviedTests' do

end

target 'SambaTechMoviedUITests' do

end

