
platform :ios, '8.0'
use_frameworks!

target 'SambaTechMovied' do
    pod 'Alamofire'
    pod 'AlamofireObjectMapper'
end

target 'SambaTechMoviedTests' do

end

target 'SambaTechMoviedUITests' do

end

